name: proto_benchmark
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  protobuf: 5.0.0
  path: ^1.9.0
  ffi: ^2.1.3
  fixnum: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
